version: '3'

networks:
  jp_api_v1:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: jp_api_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
      - ../_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - jp_api_v1

  mysql:
    image: mysql:5.7.22
    container_name: jp_api_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ../_docker/api_database/mysql:/var/lib/mysql
      - ../_docker/api_database/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: jsp_project
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - jp_api_v1

  php:
    hostname: docker-php
    build:
      context: .
      dockerfile: ../_docker/php-build
    container_name: jp_api_php
    volumes:
      - .:/var/www/html/
    ports:
      - "9000:9000"
    networks:
      - jp_api_v1
