version: '3'

networks:
  jp_api_v1:

services:
  memcached:
    image: memcached:latest
    networks:
      - jp_api_v1

  mysql:
    image: mysql:5.7.22
    container_name: jp_api_mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./_docker/database/mysql:/var/lib/mysql
      - ./_docker/database/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: jsp_project
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - jp_api_v1

  php:
    hostname: docker-php
    build:
      context: .
      dockerfile: ./_docker/build-files/apache-build
    container_name: jp_api_php
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysql
    ports:
      - "9000:9000"
      - "8080:80"
    networks:
      - jp_api_v1
