<?php

declare(strict_types=1);

/**
 * This file is part of Joshua Project API.
 *
 * Joshua Project API is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Joshua Project API is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see
 * <http://www.gnu.org/licenses/>.
 *
 * @author Johnathan Pulos <johnathan@missionaldigerati.org>
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 *
 */

namespace Tests\v1\Integration;

use Doctrine\DBAL\Connection;
use Tests\Support\GuzzleHttpClient;
use PHPUnit\Framework\TestCase;

/**
 * The class for testing integration of the Static Pages
 *
 * @package default
 * @author Johnathan Pulos
 */
class StaticPagesTest extends TestCase
{
    /**
     * The HTTP Client Object
     *
     * @var GuzzleHttpClient
     */
    public GuzzleHttpClient $httpClient;
    /**
     * The PDO database connection object
     *
     * @var Connection
     */
    private Connection $db;
    /**
     * The current API version number
     *
     * @var string
     * @access private
     **/
    private string $APIVersion;
    /**
     * The URL for the testing server
     *
     * @var string
     * @access private
     **/
    private string $siteURL;

    /**
     * Set up the test class
     *
     * @return void
     * @access public
     * @author Johnathan Pulos
     */
    public function setUp(): void
    {
        $this->APIVersion = $_ENV['api_version'];
        $this->siteURL = $_ENV['site_url'];
        $this->httpClient = new GuzzleHttpClient();
        $this->db = getDatabaseInstance();
    }
    /**
     * Runs at the end of each test
     *
     * @access public
     * @author Johnathan Pulos
     */
    public function tearDown(): void
    {
        $this->httpClient->clearCache();
        /**
         * Clear all the api_keys generated by the test
         *
         * @author Johnathan Pulos
         */
        $this->db->executeStatement("DELETE FROM `md_api_keys` WHERE `api_usage` = 'testing'");
    }
    /**
     * Users should be able to access the Home Page
     *
     * @return void
     * @author Johnathan Pulos
     */
    public function testWebsiteShouldDisplayTheHomePage(): void
    {
        $response = $this->httpClient->get(
            $this->siteURL . "/",
            [],
            "show_home"
        );
        $this->assertEquals(200, $this->httpClient->responseCode);
    }
    /**
     * Users should be able to access the Terms of Use Page
     *
     * @return void
     * @author Johnathan Pulos
     */
    public function testWebsiteShouldDisplayTheTermsOfUsePage(): void
    {
        $response = $this->httpClient->get(
            $this->siteURL . "/terms_of_use",
            [],
            "show_terms_of_use"
        );
        $this->assertEquals(200, $this->httpClient->responseCode);
        $this->assertStringContainsString('<h2>API Terms of Use</h2>', $response);
    }
    /**
     * Users should be able to get their API Key
     *
     * @return void
     * @author Johnathan Pulos
     */
    public function testWebsiteShouldAllowUsersToGetAnAPIKeyIfValidAuthorizationKey(): void
    {
        $authorizationToken = 'l543g3$4';
        $expectedAPIKey = generateRandomKey(12);
        $this->db->executeStatement(
            "INSERT INTO md_api_keys (api_usage, api_key, authorize_token, status, created) VALUES ('testing', :api_key, :token, 0, NOW())",
            ['api_key' => $expectedAPIKey, 'token' => $authorizationToken]
        );
        $response = $this->httpClient->get(
            $this->siteURL . "/get_my_api_key",
            ['authorize_token' => $authorizationToken],
            "get_my_api_key"
        );
        deleteApiKey($expectedAPIKey);
        $this->assertEquals(200, $this->httpClient->responseCode);
        $this->assertNotEquals(false, strpos(strtolower($response), 'api key has been activated'));
    }
    /**
     * Users should see warning if API Key is already active
     *
     * @return void
     * @author Johnathan Pulos
     */
    public function testWebsiteShouldTellUsersThatAPIKeyAlreadyUpdated(): void
    {
        $authorizationToken = 'l543g3$4Ac';
        $expectedAPIKey = generateRandomKey(12);
        $this->db->executeStatement(
            "INSERT INTO md_api_keys (api_usage, api_key, authorize_token, status, created)" .
            " VALUES ('testing', :api_key, :token, 1, NOW())",
            ['api_key' => $expectedAPIKey, 'token' => $authorizationToken]
        );
        $response = $this->httpClient->get(
            $this->siteURL . "/get_my_api_key",
            ['authorize_token' => $authorizationToken],
            "get_my_api_key_active_key"
        );
        deleteApiKey($expectedAPIKey);
        $this->assertEquals(200, $this->httpClient->responseCode);
        $this->assertNotEquals(false, strpos(strtolower($response), 'api key was already activated'));
    }
    /**
     * Users should see warning if API Key has been suspended
     *
     * @return void
     * @author Johnathan Pulos
     */
    public function testWebsiteShouldTellUsersThatAPIKeyIsSuspended(): void
    {
        $authorizationToken = 'l543g3$4Ac';
        $expectedAPIKey = generateRandomKey(12);
        $this->db->executeStatement(
            "INSERT INTO md_api_keys (api_usage, api_key, authorize_token, status, created) VALUES ('testing', :api_key, :token, 2, NOW())",
            ['api_key' => $expectedAPIKey, 'token' => $authorizationToken]
        );
        $response = $this->httpClient->get(
            $this->siteURL . "/get_my_api_key",
            ['authorize_token' => $authorizationToken],
            "get_my_api_key_suspended_key"
        );
        deleteApiKey($expectedAPIKey);
        $this->assertEquals(200, $this->httpClient->responseCode);
        $this->assertNotEquals(false, strpos(strtolower($response), 'api key was suspended'));
    }
    /**
     * Users should see error if the Authorization Token is Missing
     *
     * @return void
     * @author Johnathan Pulos
     */
    public function testWebsiteShouldWarnUsersWhenTheAuthorizationTokenIsMissing(): void
    {
        $authorizationToken = 'l543g3$4Ac';
        $expectedAPIKey = 'AKey$43Ac';
        $this->db->executeStatement(
            "INSERT INTO md_api_keys (api_usage, api_key, authorize_token, status, created) VALUES ('testing', :api_key, :token, 2, NOW())",
            ['api_key' => $expectedAPIKey, 'token' => $authorizationToken]
        );
        $response = $this->httpClient->get(
            $this->siteURL . "/get_my_api_key",
            ['authorize_token' => ''],
            "get_my_api_key_missing_token"
        );
        deleteApiKey($expectedAPIKey);
        $this->assertEquals(200, $this->httpClient->responseCode);
        $this->assertNotEquals(false, strpos(strtolower($response), 'unable to locate your api key'));
    }
    /**
     * Users should be able to access the Resend Activation URLS page
     *
     * @return void
     * @author Johnathan Pulos
     */
    public function testWebsiteShouldDisplayTheResendActivationLinkPage(): void
    {
        $response = $this->httpClient->get(
            $this->siteURL . "/resend_activation_links",
            [],
            "show_resend_activation_links"
        );
        $this->assertEquals(200, $this->httpClient->responseCode);
    }
}
