<?php
/**
 * This file is part of Joshua Project API.
 * 
 * Joshua Project API is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Joshua Project API is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see 
 * <http://www.gnu.org/licenses/>.
 *
 * @author Johnathan Pulos <johnathan@missionaldigerati.org>
 * @copyright Copyright 2013 Missional Digerati
 * @todo Remove the following fields from the query results (JPScalePC, LeastReachedPC, RLG3PC, PrimaryReligionPC, JPScalePGAC, LeastReachedPGAC, 
 * RLG3PGAC, PrimaryReligionPGAC, ROL3Edition14Orig, EthnologueCountryCode, EthnologueMapExists, WorldMapExists, UNMap, EthneMonth) also fields starting
 * with OW, HDI
 * 
 */
namespace QueryGenerators;

/**
 * A class that creates the prepared statement, and sets up the variables for a PDO prepared statement query.
 * These queries specifically work with the PeopleGroup data.
 *
 * @package default
 * @author Johnathan Pulos
 */
class PeopleGroup
{
    /**
     * The prepared statement generated by the class to be used with PDO
     *
     * @var string
     * @access public
     */
    public $preparedStatement = "";
    /**
     * The variables for the prepared statement
     *
     * @var array
      * @access public
     */
    public $preparedVariables = array();
    /**
     * The provided parameters passed in from the $_GET params
     *
     * @var array
      * @access private
     */
    private $providedParams = array();
    /**
     * The table to pull the data from
     *
     * @var string
     * @access private
     */
    private $tableName = "jppeoples";
    /**
     * Construct the class
     *
     * @param array $getParams the params to use for the query.  Each message has required fields, and will throw error
     * if they are missing
     * 
     * @access public
     * @author Johnathan Pulos
     */
    public function __construct($getParams)
    {
        $this->providedParams = $getParams;
        $this->cleanParams();
    }
    /**
     * Get the unreached of the day query statement.  Requires a month and day param in the given params.
     * REQUIRES getParams month & day
     * 
     * @return void
     * @access public
     * @author Johnathan Pulos
     */
    public function dailyUnreached()
    {
        $this->validateProvidedParams(array('month', 'day'));
        if ($this->validateVariableInRange('month', 1, 12) === false) {
            throw new \InvalidArgumentException("The month is out of range.  It should be 1-12.");
        }
        if ($this->validateVariableInRange('day', 1, 31) === false) {
            throw new \InvalidArgumentException("The day is out of range.  It should be 1-31.");
        }
        $month = intval($this->providedParams['month']);
        $day = intval($this->providedParams['day']);
        $this->preparedStatement = "SELECT * FROM jppeoples WHERE LRofTheDayMonth = :month AND LRofTheDayDay = :day LIMIT 1";
        $this->preparedVariables = array('month' => $month, 'day' => $day);
    }
    /**
     * Find the People Group using the id (PeopleID3), and the country (ROG3)
     *
     * @return void
     * @access public
     * @author Johnathan Pulos
     */
    public function findByIdAndCountry()
    {
        $this->validateProvidedParams(array('id', 'country'));
        $id = intval($this->providedParams['id']);
        $country = strtoupper($this->providedParams['country']);
        $this->preparedStatement = "SELECT * FROM jppeoples WHERE PeopleID3 = :id AND ROG3 = :country LIMIT 1";
        $this->preparedVariables = array('id' => $id, 'country' => $country);
    }
    /**
     * Find the People Group by ID (PeopleID3)
     *
     * @return void
     * @access public
     * @author Johnathan Pulos
     */
    public function findById()
    {
        $this->validateProvidedParams(array('id'));
        $id = intval($this->providedParams['id']);
        $this->preparedStatement = "SELECT * FROM jppeoples WHERE PeopleID3 = :id";
        $this->preparedVariables = array('id' => $id);
    }
    /**
     * Find all the People Groups using filters passed in the GET params
     *
     * @return void
     * @access public
     * @author Johnathan Pulos
     */
    public function findAllWithFilters()
    {
        $where = "";
        $appendAndOnWhere = false;
        $this->preparedStatement = "SELECT * FROM jppeoples";
        if ($this->paramExists('people_id1')) {
            $where .= $this->generateInStatementFromPipedString($this->providedParams['people_id1'], 'PeopleID1');
            $appendAndOnWhere = true;
        }
        if ($this->paramExists('people_id2')) {
            if ($appendAndOnWhere === true) {
                $where .= " AND ";
            }
            $where .= $this->generateInStatementFromPipedString($this->providedParams['people_id2'], 'PeopleID2');
            $appendAndOnWhere = true;
        }
        if ($this->paramExists('people_id3')) {
            if ($appendAndOnWhere === true) {
                $where .= " AND ";
            }
            $where .= $this->generateInStatementFromPipedString($this->providedParams['people_id3'], 'PeopleID3');
            $appendAndOnWhere = true;
        }
        if ($this->paramExists('rop1')) {
            if ($appendAndOnWhere === true) {
                $where .= " AND ";
            }
            $where .= $this->generateInStatementFromPipedString($this->providedParams['rop1'], 'ROP1');
            $appendAndOnWhere = true;
        }
        if ($this->paramExists('rop2')) {
            if ($appendAndOnWhere === true) {
                $where .= " AND ";
            }
            $where .= $this->generateInStatementFromPipedString($this->providedParams['rop2'], 'ROP2');
            $appendAndOnWhere = true;
        }
        if ($this->paramExists('rop3')) {
            if ($appendAndOnWhere === true) {
                $where .= " AND ";
            }
            $where .= $this->generateInStatementFromPipedString($this->providedParams['rop3'], 'ROP3');
            $appendAndOnWhere = true;
        }
        if ($where != "") {
            $this->preparedStatement .= " WHERE " . $where;
        }
        $this->preparedStatement .= " ORDER BY PeopleID1 ASC ";
        $this->addLimitFilter();
    }
    /**
     * Set the limit and starting variables based on the given limit and page variables
     *
     * @return void
     * @access private
     * @author Johnathan Pulos
     */
    private function addLimitFilter()
    {
        if (($this->paramExists('limit')) && intval($this->providedParams['limit']) > 0) {
            $this->preparedVariables['limit'] = intval($this->providedParams['limit']);
        } else {
            $this->preparedVariables['limit'] = 100;
        }
        if (($this->paramExists('page')) && intval($this->providedParams['page']) > 0) {
            $this->preparedVariables['starting'] = (intval($this->providedParams['page'])*$this->preparedVariables['limit'])-1;
        } else {
            $this->preparedVariables['starting'] = 0;
        }
        $this->preparedStatement .= "LIMIT :starting, :limit";
    }
    /**
     * Generates an IN () statement from a piped string.  It writes the prepared version, and adds the variables to the preparedVariables params.
     * @example 17|23|12 -> IN (17, 23, 12)
     *
     * @param string $str The piped string
     * @param string $columnName the column name that you want to search
     * @return string
     * @access private
     * @author Johnathan Pulos
     */
    private function generateInStatementFromPipedString($str, $columnName)
    {
        $preparedInVars = array();
        $i = 0;
        $stringParts = explode("|", $str);
        foreach ($stringParts as $element) {
            $preparedParamName = str_replace(' ', '', strtolower($columnName)) . '_' . $i;
            array_push($preparedInVars, ':' . $preparedParamName);
            $this->preparedVariables[$preparedParamName] = $element;
            $i = $i+1;
        }
        return $columnName . " IN (" . join(", ", $preparedInVars) . ")";
    }
    /**
     * A shorter method for checking if the array_key_exists
     *
     * @param string $paramName the name of the param your looking for
     * @return void
     * @access private
     * @author Johnathan Pulos
     */
    private function paramExists($paramName)
    {
        return array_key_exists($paramName, $this->providedParams);
    }
    /**
     * Checks if the params were set in the __construct() method of this class on providedParams. If not, then throw an error.
     *
     * @param array $params the keys of the required params
     * @return void
     * @access private
     * @author Johnathan Pulos
     */
    private function validateProvidedParams($params)
    {
        foreach ($params as $key) {
            if (array_key_exists($key, $this->providedParams) === false) {
                throw new \InvalidArgumentException("Missing the required parameter " . $key);
            }
        }
    }
    /**
     * validates a integer is in range
     *
     * @param string $key the key of the $this->providedParams param to test
     * @param integer $start the start of the range
     * @param integer $end the end of the range
     * @return boolean
     * @access public
     * @author Johnathan Pulos
     */
    private function validateVariableInRange($key, $start, $end)
    {
        $var = intval($this->providedParams[$key]);
        return (($var >= $start) && ($var <= $end));
    }
    /**
     * Cleans the parameters passed to $this->providedParams variable.
     *
     * @return void
     * @access private
     * @author Johnathan Pulos
     */
    private function cleanParams()
    {
        $newValue = array();
        foreach ($this->providedParams as $key => $value) {
            $newValue[$key] = strip_tags($value);
        }
        $this->providedParams = $newValue;
    }
}
